import logging
from fastapi import APIRouter, WebSocket, WebSocketDisconnect, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from typing import List

from app.database.session import get_db
from app.database.models import Log, Project
from app.schemas.analysis import LogResponse
from app.api.v1.auth import get_current_user
from app.database.models import User
from app.agents.planner import active_sockets

logger = logging.getLogger(__name__)

router = APIRouter()

@router.get("/logs/{project_id}", response_model=List[LogResponse])
async def list_agent_logs(
    project_id: int,
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """Retrieves step logs generated by the agent workflow for a project."""
    # Verify access
    proj_check = await db.execute(
        select(Project).where(Project.id == project_id, Project.owner_id == current_user.id)
    )
    if not proj_check.scalar_one_or_none():
        raise HTTPException(status_code=403, detail="Not authorized to access project details.")
        
    result = await db.execute(
        select(Log)
        .where(Log.project_id == project_id)
        .order_by(Log.created_at.asc())
    )
    return result.scalars().all()

@router.websocket("/ws/{project_id}")
async def websocket_endpoint(websocket: WebSocket, project_id: int):
    """WebSocket route mapping connection state to allow live broadcast of analysis progress."""
    await websocket.accept()
    
    # Register socket in global channels list
    if project_id not in active_sockets:
        active_sockets[project_id] = []
    active_sockets[project_id].append(websocket)
    
    try:
        # Keep connection open waiting for client keep-alive or close alerts
        while True:
            # We can read messages if client wants to command operations, or just block-sleep
            data = await websocket.receive_text()
            # Echo keepalive or command
            await websocket.send_text(f"ACK: {data}")
    except WebSocketDisconnect:
        # Remove connection from list
        if project_id in active_sockets and websocket in active_sockets[project_id]:
            active_sockets[project_id].remove(websocket)
            if not active_sockets[project_id]:
                del active_sockets[project_id]
        logger.info(f"WebSocket client disconnected for project {project_id}")
    except Exception as e:
        logger.error(f"WebSocket connection error for project {project_id}: {e}")
        if project_id in active_sockets and websocket in active_sockets[project_id]:
            active_sockets[project_id].remove(websocket)
